machine:
  node:
    version: 8.11.1
  environment:
    CONTINUOUS_INTEGRATION: true

dependencies:
  cache_directories:
    - node_modules
  override:
    - npm install

test:
  override:
    - npm run lint
    - npm test